version: '2'

tasks:
  generate:
    dir: frontend
    cmds:
      - statik -f
  build:
    dir: cmd/lights
    cmds:
      - go build -o lights
    env:
      GOARCH: arm
      GOOS: linux
      CGO_ENABLED: 0
  docker-build:
    dir: cmd/lights
    cmds:
      - docker build -t lights .
  deploy:
    dir: cmd/lights
    cmds:
      - docker stack deploy -c docker-compose.yaml lights
