version: '2'

tasks:
  generate:
    dir: frontend
    cmds:
      - statik -f
  build:
    dir: cmd/lights
    cmds:
      - go build -o lights
    env:
      GOARCH: arm
      GOOS: linux
      CGO_ENABLED: 0
  docker-build:
    dir: cmd/lights
    cmds:
      - docker build -t lights .
  deploy:
    cmds:
      - docker run -p 80:80 -d --mount type=bind,source=/sys/,destination=/sys/ --restart=always --name=lights lights
  undeploy:
    cmds:
      - docker stop lights
      - docker rm lights
